### ISSUE TITLE
Failed to activate the toggle-read-only package

### ISSUE THREAD

**Issue by kenijo** [deprint/toggle-read-only#1]
[Enter steps to reproduce below:]
1. Install the package
2. Start/restart Atom
3. An error message shows up saying: "Cannot read property 'endsWith' of undefined"

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [toggle-read-only](https://github.com/deprint/toggle-read-only) package, v0.1.1
### Stack Trace

Failed to activate the toggle-read-only package

```
At Cannot read property 'endsWith' of undefined

TypeError: Cannot read property 'endsWith' of undefined
    at file:///C:/Users/KJU/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:14:59
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:307:9)
    at Object.module.exports.activate (file:///C:/Users/KJU/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:10:45)
    at Package.module.exports.Package.activateNow (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\KJU\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ftp-deployment, v0.4.0
atom-json-color, v0.4.2
atom-shell-commands, v1.4.0
atom-sync, v0.7.3
atom-user-commands, v0.1.4
atomic-sync, v0.6.4
auto-detect-indentation, v1.1.0
auto-indent, v0.5.0
bottom-dock, v0.4.4
command-executor, v1.4.2
commands, v0.0.1
comment-newline, v1.0.0
file-type-icons, v1.3.0
formatter-jsbeautify, v1.0.2
formatter-json, v1.0.1
formatter-tidy, v1.0.1
imdone-atom, v1.3.29
language-csv, v1.1.2
logo-file-icons, v1.1.6
npm-outdated, v0.5.0
open-no-binaries, v0.1.1
persistent-undo, v1.2.0
php-cs-fixer, v2.5.6
prime-file-icons, v0.2.2
process-palette, v0.8.1
remote-atom, v1.3.9
remote-atom-plus, v0.1.0
remote-edit, v1.8.24
Remote-FTP, v0.8.3
remote-sync, v4.1.2
symbols-list, v2.2.0
symbols-plus, v0.1.1
todo-manager, v0.2.9
toggle-read-only, v0.1.1
unfancy-file-icons, v0.7.0

# Dev
No dev packages
```

**Comment by fstiewitz** [comment]
Apparently my package didn't like untitled buffers. Thanks for the report.
