### ISSUE TITLE
Uncaught TypeError: _this.getTitle is not a function

### ISSUE THREAD

**Issue by ghost** [deprint/toggle-read-only#2]
[Enter steps to reproduce below:]
1. Open several files.
2. Right click on one of the ope tabs and click 'Split Right'.
3. Double-click on the tab that you split right, as you would normally do to make it read-only.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [toggle-read-only](https://github.com/deprint/toggle-read-only) package, v0.1.2
### Stack Trace

Uncaught TypeError: _this.getTitle is not a function

```
At /Users/jamesroberts/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:218

TypeError: _this.getTitle is not a function
    at /Users/jamesroberts/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:218:56
    at Function.module.exports.Emitter.simpleDispatch (/Users/jamesroberts/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/jamesroberts/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Object.module.exports.disableReadOnly (/Users/jamesroberts/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:38:20)
    at Object.module.exports.toggleReadOnly (/Users/jamesroberts/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:23:8)
    at TextEditor.editor.terminatePendingState (/Users/jamesroberts/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:12:44)
    at atom-tabs.TabBarView.onDoubleClick (/Users/jamesroberts/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:675:87)
```
### Commands

```
  2x -0:38.4.0 tabs:split-right (li.texteditor.tab.sortable.active.right-clicked)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
fold-functions, v0.4.3
toggle-read-only, v0.1.2

# Dev
No dev packages
```

**Comment by fstiewitz** [comment]
Thanks for the report. Unfortunately, I had to remove the ability to toggle the package by clicking on an editors tab item (this feature was already broken) in order to fix it.
